### ISSUE TITLE
Add support for Mollie Components

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-mollie#15]
From customer:

> With the Pronamic plugin, is it possible to display the Mollie payment module directly in the form (in the page of the form) created via Formidable Form?
> 
> Mollie presents this direct integration option as "Mollie Components", I wanted to know if this option is enabled by default.

- https://docs.mollie.com/components/overview
- Related (as usage of online card payments will increase): the upcoming transition from Maestro to Debit Mastercard cards
  - https://www.adyen.com/nl_NL/blog/Debit-Mastercard-vervangt-Maestro--dit-is-wat-je-wil-weten

**Comment by rvdsteege** [comment]
PoC in branch https://github.com/pronamic/wp-pronamic-pay-mollie/tree/mollie-components

<img width="772" alt="Scherm­afbeelding 2022-11-30 om 09 54 38" src="https://user-images.githubusercontent.com/10371164/204751329-aaeb34a8-844e-4274-8886-2d541c5b95fe.png">

<img width="542" alt="Scherm­afbeelding 2022-11-30 om 09 55 28" src="https://user-images.githubusercontent.com/10371164/204751503-687b654a-8463-4e9f-9586-cfbcf10f8ef5.png">

**Comment by rvdsteege** [comment]
I checked the current status of this issue, but as it requires explicit integration with extensions (to first retrieve the token before submitting the checkout form) it might be better suited for a dedicated plugin integrating Mollie with WooCommerce?

For example, code like this is not at home in this repository:
- https://github.com/pronamic/wp-pronamic-pay-mollie/blob/4ffd4abd6bf20665f41e863966673c4d702e134f/js/src/components.js#L147-L172

**Comment by remcotolsma** [comment]
Discussed this today with @rvdsteege @pronamic HQ and we think this is a nice feature for Pronamic Pay 9.7. The specific WooCommerce code must be able to be edited out, for example by using `input.form`.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#instance_properties_related_to_the_parent_form

We can also introduce a credit card field in core so that this field does not have to be constructed via JavaScript. We then only have to mount the Mollie components to the subfields of our core credit card field.
